import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

/**
 * Schema for individual excerpt chunks (generated by setup.ts)
 * Each chunk file contains excerpts for a specific section of a collection.
 */
const excerptChunks = defineCollection({
    loader: glob({ pattern: '**/*.json', base: './src/content/excerpt-chunks' }),
    schema: z.object({
        sectionId: z.string(),
        chunkIndex: z.number(),
        excerptIds: z.array(z.string()),
        excerpts: z.array(
            z.object({
                id: z.string(),
                from: z.number(),
                nass: z.string(),
                text: z.string(),
                translator: z.number(),
                lastUpdatedAt: z.number(),
                meta: z
                    .object({
                        // Hadith metadata
                        num: z.string().optional(),
                        // Book metadata
                        type: z.enum(['B', 'C']).optional(),
                        vol: z.number().optional(),
                        vp: z.number().optional(),
                    })
                    .optional(),
            }),
        ),
    }),
});

export const collections = {
    'excerpt-chunks': excerptChunks,
};
